// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfATm072Iwd83WDHufLUJQhiRa-M8GNao',
    appId: '1:602137511185:web:153408e25c3691d2ffb8b0',
    messagingSenderId: '602137511185',
    projectId: 'prakflutterfirebase-9d1f1',
    authDomain: 'prakflutterfirebase-9d1f1.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-9d1f1.appspot.com',
    measurementId: 'G-JNKL61ND59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi1wxqK1QBT84JahA4T3YHsjW1efjfsDE',
    appId: '1:602137511185:android:ed31eee3ad4e0e0affb8b0',
    messagingSenderId: '602137511185',
    projectId: 'prakflutterfirebase-9d1f1',
    storageBucket: 'prakflutterfirebase-9d1f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5sX7ut5bsOqKbSmfcceo1clPuCFm2YY',
    appId: '1:602137511185:ios:0fa07417060bb2d9ffb8b0',
    messagingSenderId: '602137511185',
    projectId: 'prakflutterfirebase-9d1f1',
    storageBucket: 'prakflutterfirebase-9d1f1.appspot.com',
    iosBundleId: 'com.example.praktikum6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5sX7ut5bsOqKbSmfcceo1clPuCFm2YY',
    appId: '1:602137511185:ios:0fa07417060bb2d9ffb8b0',
    messagingSenderId: '602137511185',
    projectId: 'prakflutterfirebase-9d1f1',
    storageBucket: 'prakflutterfirebase-9d1f1.appspot.com',
    iosBundleId: 'com.example.praktikum6',
  );
}
